const primitives = {
  spacing: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 44,
    12: 48,
  },
  colors: {
    base: {
      white: '#ffffff',
      black: '#1e1f20',
      red: '#ff3b2f',
      orange: '#ff9500',
      green: '#35c759',
      mint: '#04c7be',
      teal: '#30b0c7',
      cyan: '#31ade6',
      indigo: '#5856d7',
    },
    blue: {
      50: '#e3f2fd',
      100: '#bbdefb',
      200: '#90caf9',
      300: '#64b5f6',
      400: '#42a5f5',
      500: '#2196f3',
      600: '#1e88e5',
      700: '#1976d2',
      800: '#1565c0',
      900: '#0d47a1',
    },
    yellow: {
      50: '#fffde7',
      100: '#fff9c4',
      200: '#fff59d',
      300: '#fff076',
      400: '#ffee58',
      500: '#ffeb3b',
      600: '#fdd836',
      700: '#fbc02d',
      800: '#f9a925',
      900: '#f57f16',
    },
    gray: {
      100: '#f8f9fa',
      200: '#eaecef',
      300: '#dee2e6',
      400: '#ced4da',
      500: '#acb5bd',
      600: '#6c757d',
      700: '#495057',
      800: '#343a40',
      900: '#212529',
    },
  },
};

const lightTheme = {
  colors: {
    surfacePrimary: primitives.colors.base.white,
    buttonBackgroundPrimary: primitives.colors.blue[600],
    buttonLabelPrimary: primitives.colors.base.white,
    textPrimary: primitives.colors.gray[900],
    textSecondary: primitives.colors.gray[500],
    containerPrimary: primitives.colors.blue[300],
    warning: primitives.colors.yellow[500],
    navContainer: primitives.colors.gray[100],
    navIcon: primitives.colors.gray[800],
    selected: primitives.colors.blue[800],
    containerSecondary: primitives.colors.blue[100],
    toggleContainer: primitives.colors.gray[200],
    toggleButton: primitives.colors.blue[300],
    error: primitives.colors.base.red,
    sensor1: primitives.colors.base.indigo,
    sensor2: primitives.colors.yellow[800],
    sensor3: primitives.colors.base.teal,
  },
  spacing: {
    spacingNone: primitives.spacing[0],
    spacingXxs: primitives.spacing[1],
    spacingXs: primitives.spacing[2],
    spacingSm: primitives.spacing[3],
    spacingMd: primitives.spacing[4],
    spacingLg: primitives.spacing[5],
    spacingXlg: primitives.spacing[6],
    spacing2xl: primitives.spacing[7],
    spacing3xl: primitives.spacing[8],
    spacing4xl: primitives.spacing[9],
    spacing5xl: primitives.spacing[10],
    spacing6xl: primitives.spacing[11],
    spacing7xl: primitives.spacing[12],
  },
  radius: {
    radiusNone: primitives.spacing[0],
    radiusXxs: primitives.spacing[1],
    radiusXs: primitives.spacing[2],
    radiusSm: primitives.spacing[3],
    radiusMd: primitives.spacing[4],
    radiusLg: primitives.spacing[5],
    radiusXlg: primitives.spacing[6],
  },
  icon: {
    iconXs: primitives.spacing[2],
    iconSm: primitives.spacing[3],
    iconMd: primitives.spacing[4],
    iconLg: primitives.spacing[5],
    iconXlg: primitives.spacing[6],
  },
  homeImageUrl: '../assets/homeLight.png',
};

const darkTheme = {
  colors: {
    surfacePrimary: primitives.colors.base.black,
    buttonBackgroundPrimary: primitives.colors.blue[400],
    buttonLabelPrimary: primitives.colors.base.black,
    textPrimary: primitives.colors.gray[100],
    textSecondary: primitives.colors.gray[500],
    containerPrimary: primitives.colors.blue[600],
    warning: primitives.colors.yellow[500],
    navContainer: primitives.colors.gray[900],
    navIcon: primitives.colors.gray[200],
    selected: primitives.colors.blue[200],
    containerSecondary: primitives.colors.blue[900],
    toggleContainer: primitives.colors.gray[800],
    toggleButton: primitives.colors.blue[700],
    error: primitives.colors.base.red,
    sensor1: primitives.colors.base.indigo,
    sensor2: primitives.colors.yellow[200],
    sensor3: primitives.colors.base.teal,
  },
  spacing: {
    spacingNone: primitives.spacing[0],
    spacingXxs: primitives.spacing[1],
    spacingXs: primitives.spacing[2],
    spacingSm: primitives.spacing[3],
    spacingMd: primitives.spacing[4],
    spacingLg: primitives.spacing[5],
    spacingXlg: primitives.spacing[6],
    spacing2xl: primitives.spacing[7],
    spacing3xl: primitives.spacing[8],
    spacing4xl: primitives.spacing[9],
    spacing5xl: primitives.spacing[10],
    spacing6xl: primitives.spacing[11],
    spacing7xl: primitives.spacing[12],
  },
  radius: {
    radiusNone: primitives.spacing[0],
    radiusXxs: primitives.spacing[1],
    radiusXs: primitives.spacing[2],
    radiusSm: primitives.spacing[3],
    radiusMd: primitives.spacing[4],
    radiusLg: primitives.spacing[5],
    radiusXlg: primitives.spacing[6],
  },
  icon: {
    iconXs: primitives.spacing[2],
    iconSm: primitives.spacing[3],
    iconMd: primitives.spacing[4],
    iconLg: primitives.spacing[5],
    iconXlg: primitives.spacing[6],
  },
  homeImageUrl: '../assets/homeDark.png',
};

export {primitives, lightTheme, darkTheme};
